title: Stackbit Fresh Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_style: overflow
palette: blue
header:
  title: Prithviraj sukale
  tagline: "I am a full Stack Rails developer based in Pune, India. I have a bachelor’s degree in computer science and engineering.\r\n"
  profile_img: >-
    https://res.cloudinary.com/practicaldev/image/fetch/s--iZ6-YUlr--/c_fill,f_auto,fl_progressive,h_320,q_auto,w_320/https://thepracticaldev.s3.amazonaws.com/uploads/user/profile_image/19200/27fa382a-b657-42f1-8def-02d19410f320.jpg
  bg: dark
  has_nav: true
  has_social: true
footer:
  content: '&copy; All rights reserved.'
  links:
    - text: Made with Stackbit
      url: 'https://www.stackbit.com'
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
